services:
  app:
    container_name: fe-angular-game-price-comparator
    build:
      context: .
      dockerfile: ./.ops/Dockerfile
    image: fe-angular-game-price-comparator:v1
    ports:
      - 4200:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge